name: RUoM
version: "${project.version}"
main: me.Mohamad82.RUoM.RUoM
api-version: 1.13
authors: [ Mohamad82 ]
softdepends: [ Vault, WorldEdit, FAWE, MMOItems, Oraxen, Essentials ]
description: A custom exclusive utils
commands:
  ruom:
