name: RUoM
version: "${version}"
main: me.mohamad82.ruom.test.TestMain
api-version: 1.13
authors: [ Mohamad82 ]
softdepends: [ Vault, WorldEdit, FAWE, MMOItems, Oraxen, Essentials ]
description: A custom exclusive utils
commands:
  ruom:
